package com.example.tareafinal.provider

import com.example.tareafinal.R
import com.example.tareafinal.model.Planeta

object PlanetasProvider {
    val planetas = arrayListOf(
        Planeta("Mercurio: El mensajero del Sol", "Mercurio es el planeta más cercano al Sol y el más pequeño del sistema solar. Su diámetro es de aproximadamente 4,880 kilómetros, lo que lo hace un poco más grande que nuestra Luna. Debido a su proximidad al Sol, completa una órbita en solo 88 días terrestres. Sin embargo, su rotación es mucho más lenta: un día en Mercurio dura casi 59 días terrestres.\n" +
                "\n" +
                "La superficie de Mercurio está llena de cráteres, similares a los de la Luna, formados por impactos de meteoritos y cometas. Su atmósfera es extremadamente delgada, compuesta principalmente de oxígeno, sodio y potasio, lo que no le permite retener calor. Por ello, Mercurio experimenta las mayores variaciones de temperatura del sistema solar, con hasta 430 °C durante el día y -180 °C por la noche.", R.drawable.mercurio),
        Planeta("Venus: La joya ardiente del cielo", "Venus es el segundo planeta más cercano al Sol y a menudo es llamado el \"gemelo de la Tierra\" debido a su tamaño y composición similares. Su diámetro es de aproximadamente 12,104 kilómetros, lo que lo convierte en el tercer planeta más pequeño del sistema solar, después de Mercurio y Marte. Completa una órbita alrededor del Sol en 225 días terrestres, pero su rotación es extremadamente lenta y en sentido retrógrado: un día en Venus dura 243 días terrestres.\n" +
                "\n" +
                "La superficie de Venus está cubierta de vastas llanuras volcánicas, montañas y numerosos cráteres, envuelta en una densa atmósfera de dióxido de carbono y nubes de ácido sulfúrico. Esta atmósfera crea un efecto invernadero extremo que eleva las temperaturas superficiales hasta unos abrasadores 475 °C, haciéndolo incluso más caliente que Mercurio, a pesar de estar más lejos del Sol.", R.drawable.venus),
        Planeta("Tierra: El hogar de la vida", "La Tierra es el tercer planeta más cercano al Sol y el único conocido que alberga vida. Con un diámetro de aproximadamente 12,742 kilómetros, es el quinto planeta más grande del sistema solar. Su órbita alrededor del Sol dura 365.25 días, lo que define nuestro año, y su rotación sobre su eje tarda 24 horas, creando los días y las noches.\n" +
                "\n" +
                "La superficie de la Tierra está compuesta en un 71% por agua y en un 29% por tierra firme, incluyendo montañas, valles, desiertos y bosques. Su atmósfera está formada principalmente por nitrógeno y oxígeno, lo que permite respirar y protege al planeta de radiaciones solares nocivas y pequeños impactos de meteoritos. Además, cuenta con una magnetosfera que desvía partículas cargadas del viento solar, contribuyendo a su habitabilidad.", R.drawable.tierra),
        Planeta("Marte: El planeta rojo", "Marte es el cuarto planeta desde el Sol y el segundo más pequeño del sistema solar, con un diámetro de aproximadamente 6,779 kilómetros, casi la mitad del tamaño de la Tierra. Su característico color rojo se debe a la abundancia de óxido de hierro en su superficie. Marte tarda 687 días terrestres en completar una órbita alrededor del Sol, mientras que su día, llamado sol, dura solo 24.6 horas, muy similar al día terrestre.\n" +
                "\n" +
                "La superficie marciana está marcada por vastos desiertos, enormes volcanes, como el Monte Olimpo, el más alto del sistema solar, y profundos cañones, como Valles Marineris. Aunque su atmósfera es muy delgada, compuesta principalmente de dióxido de carbono, en el pasado Marte pudo haber tenido ríos, lagos e incluso océanos. Hoy, agua en estado sólido se encuentra en sus polos y bajo su superficie.", R.drawable.marte),
        Planeta("Júpiter: El gigante del sistema solar", "Júpiter es el quinto planeta desde el Sol y, con un diámetro de aproximadamente 139,820 kilómetros, es el más grande del sistema solar. Su inmensa masa es más de dos veces mayor que la de todos los demás planetas combinados. Completa una órbita alrededor del Sol en 11.86 años terrestres, pero tiene una rotación increíblemente rápida: un día en Júpiter dura solo 10 horas.\n" +
                "\n" +
                "Este gigante gaseoso está compuesto principalmente de hidrógeno y helio, y carece de una superficie sólida. Su atmósfera es famosa por sus bandas de nubes coloridas y tormentas masivas, incluida la Gran Mancha Roja, una tormenta anticiclónica que ha estado activa durante al menos 300 años. Júpiter también tiene un sistema de anillos delgados y más de 90 lunas confirmadas, incluidas las cuatro lunas galileanas: Ío, Europa, Ganimedes y Calisto.", R.drawable.jupiter),
        Planeta("Saturno: El señor de los anillos", "Saturno es el sexto planeta desde el Sol y el segundo más grande del sistema solar, con un diámetro de aproximadamente 120,536 kilómetros. Este gigante gaseoso tarda 29.5 años terrestres en completar una órbita alrededor del Sol, mientras que un día en Saturno dura unas 10.7 horas debido a su rápida rotación.\n" +
                "\n" +
                "Saturno es conocido por sus impresionantes y extensos anillos, compuestos principalmente de hielo y polvo, que se extienden hasta cientos de miles de kilómetros desde el planeta. Aunque está compuesto mayormente por hidrógeno y helio, su baja densidad haría que flotara en agua si existiera un océano lo suficientemente grande. Además, Saturno tiene más de 80 lunas confirmadas, entre las que destaca Titán, la segunda luna más grande del sistema solar y el único satélite con una atmósfera densa.", R.drawable.saturno),
        Planeta("Urano: El gigante inclinado", "Urano es el séptimo planeta desde el Sol y el tercer más grande del sistema solar, con un diámetro de aproximadamente 50,724 kilómetros. Es un gigante helado, compuesto principalmente de hidrógeno, helio y compuestos como agua, amoníaco y metano, que le da su característico color azul verdoso. Completa una órbita alrededor del Sol en 84 años terrestres, y su rotación es única: un día en Urano dura 17.2 horas, pero gira \"de lado\", con un eje de inclinación de 98 grados.\n" +
                "\n" +
                "Urano tiene un sistema de anillos delgados y 27 lunas conocidas, todas ellas nombradas en honor a personajes de las obras de William Shakespeare y Alexander Pope. Su atmósfera es la más fría del sistema solar, con temperaturas que descienden hasta -224 °C, debido a su baja emisión de calor interno.", R.drawable.urano),
        Planeta("Neptuno: El dios azul del viento", "Neptuno es el octavo y último planeta del sistema solar, con un diámetro de aproximadamente 49,244 kilómetros, ligeramente más pequeño que Urano. Este gigante helado tarda 165 años terrestres en completar una órbita alrededor del Sol, y su día dura 16 horas. Su color azul intenso se debe a la presencia de metano en su atmósfera, que absorbe la luz roja y refleja la azul.\n" +
                "\n" +
                "La atmósfera de Neptuno es extremadamente dinámica, con vientos supersónicos que pueden alcanzar hasta 2,100 kilómetros por hora, los más rápidos del sistema solar. Es conocido por las tormentas masivas que aparecen y desaparecen, como la Gran Mancha Oscura, una tormenta similar a la Gran Mancha Roja de Júpiter. Además, Neptuno tiene un sistema de anillos tenues y al menos 14 lunas, siendo Tritón la más grande, notable por su órbita retrógrada y su actividad geológica.", R.drawable.neptuno)
    )
}
